services:
  db:
    image: postgres:latest
    container_name: todoms-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todoms
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
